### ISSUE TITLE
Native Windows setup with MSYS2

### ISSUE THREAD

**Issue by awvwgk** [grimme-lab/qc2-teaching#22]
Currently we recommend WSL for Windows users to get their environment setup. The [MSYS2](https://www.msys2.org) project seems to provide all the necessary components (bash,git, gfortran, make, vim) to perform this course on a native Windows system without the need for WSL. We are using MSYS2 already successfully for testing of `xtb`, meaning it is capable of dealing with our usual GCC compatible software projects.

The programming can be done either in the MSYS terminal (Posix environment) by installing the packages:
```
pacman -S git gcc-fortran make vim
```

Or in the MinGW64 terminal (native Windows) by installing the packages:
```
pacman -S git mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-make vim
```

No further modification to the course material beyond the setup should be needed for this.

@MtoLStoN @Thomas3R If you have access to a Windows machine, could you give this a try to see how smooth it works for you?

**Comment by MtoLStoN** [comment]
Installed MSYS2 on a Windows machine and compiled the SCF program, that I have written during the QC2 course. Everything went smooth. Of course, Posix has some peculiarities and MS Dos was really a long time ago.
