### ISSUE TITLE
Object-oriented programming

### ISSUE THREAD

**Issue by awvwgk** [grimme-lab/qc2-teaching#34]
We currently don't cover any object-oriented programming in the Fortran introduction. However, most of our actual programs are quite heavy on object-oriented programming patterns including

- derived types for bundling data
- abstract base classes and abstract interfaces for defining contracts
- type bound procedures and procedure pointers for implementations

Two possible ways to implement this are:

1. introduce object-oriented programming in the Fortran introduction
   - explain derived types (example geometry type or basis set type)
   - provide geometry type / basis type or let students write their own types for the HF program

2. provide an additional chapter on object-oriented programming
   - use an existing object-oriented library as basis, *i.e.* [tblite](https://github.com/tblite/tblite)
   - let students implement a geometry optimizer for the xTB methods (LBFGS?)

Any other ideas?

---

Maybe worth to get some feedback from students having to learn programming in `xtb` recently (cc Albert @Albkat).

**Comment by hoelzerC** [comment]
Definitely super important to include object orientation into the already well rounded tutorial!

Imo the most important thing here is the mere "handling" of objects (vs. writing fancy OOP programs yourself). A major benefit could already be, that students understand e.g. xtb code much better and understand the benefits of agglomerating functionality into objects. Especially in the context of writing modular code, such as when combining different frameworks.

--> So really address the basics: what is a class, what is an object. What are static methods and what do you use them for. 

I think you can go through this very nicely with a simple example with molecules: a molecule class with the standard attributes (geometry, species, etc.), where you have methods that read molecules from disk, and create molecules from e.g. parsing input. 

One thing to consider would be to stick with pseudocode and  omit Fortran syntax, as it is quite complex for approaching the basics in this matter (unpopular opinion warning). If you use Fortran syntax, I guess there is little way around doing ABCs, pointer interfaces etc. As mentioned above, doing the basics right could already be a huge asset. However, it depends on how deep you want to go in the tutorial :)

**Comment by awvwgk** [comment]
> One thing to consider would be to stick with pseudocode and omit Fortran syntax, as it is quite complex for approaching the basics in this matter

I would consider pseudocode usage as harmful here, especially when exposing beginners to it (most of them program for the first time). At this stage most students are not able to translate pseudocode into actual working Fortran code without introducing typos or errors on the first try.

I think it is important to have the code snippets in a shape that they can be copied blindly by the students and just work. This way the students can gradually learn by adopting the existing code and can easily revert once they made an error which they cannot recover by themselves.
